### PR TITLE
Add order for order details

### PR DESCRIPTION
**Pull request by the-mace**
I also renamed orders.md as it seemed unclear versus this new one.

Also, some calls require more headers than others and headers in general arent covered. This new call hits a different endpoint and needs a "Dc-Cid" header in addition to the others.

### CODE REVIEW

**Comment by kaedenbrinkman** [comment]
Awesome, thanks for the additions!

> Also, some calls require more headers than others and headers in general arent covered. This new call hits a different endpoint and needs a "Dc-Cid" header in addition to the others.

Which endpoints have you found to require this header? Is it just the `/api/gql/orders/graphql` ones?

**Comment by the-mace** [comment]
Yes that seems to be the case. Some of the queries can also be pretty complex:

query user { user { email { email } phone { formatted } firstName lastName addresses { id type line1 line2 city state country postalCode } newsletterSubscription smsSubscription registrationChannels2FA userId vehicles {id highestPriorityRole __typename } orderSnapshots(filterTypes: [PRE_ORDER, VEHICLE]) { ...OrderSnapshotsFragment __typename } __typename }} fragment OrderSnapshotsFragment on OrderSnapshot { id total paidTotal subtotal state configurationStatus currency orderDate type fulfillmentSummaryStatus items { id total unitPrice quantity productDetails { ... on VehicleProduct { sku store { country __typename } __typename } ... on StandaloneProduct { sku store { country __typename } __typename } ... on ChildProduct { sku store { country __typename } __typename } __typename } configuration { basePrice ruleset { meta { locale currency country vehicle version rulesetId effectiveDate __typename } groups rules specs options defaults { basePrice initialSelection __typename } __typename } options { optionId groupId price optionDetails { name attrs price visualExterior visualInterior __typename } __typename } __typename } __typename } __typename } } }

**Comment by the-mace** [comment]
@kaedenbrinkman do you want any changes before merging this?

**Comment by kaedenbrinkman** [comment]
Looks good, just thinking `rivian-api.iml` should be removed or added to the `.gitignore`.

**Comment by the-mace** [comment]
Ok that's done

**Pull request merged**
