### PR TITLE
Add configurationStatus to vehicleOrders

### PR DESCRIPTION
**Pull request by the-mace**

### CODE REVIEW

**Comment by the-mace** [comment]
Sample response:
{'data': {'orders': {'__typename': 'OrderSearch', 'data': [{'__typename': 'Order', 'id': '247726129', 'state': 'ORDERED', 'configurationStatus': 'SOFT_LOCKED', 'fulfillmentSummaryStatus': 'READY_FOR_FULFILLMENT', 'items': [{'__typename': 'OrderItem', 'sku': 'R1T'}], 'consumerStatuses': {'__typename': 'ConsumerVehicleStatuses', 'isConsumerFlowComplete': False}}]}}}

**Comment by kaedenbrinkman** [comment]
Thanks for the addition!

**Comment by the-mace** [comment]
Sure thing. I just noticed it in other things people had done and tested it first. Wish there was a better way of discovering them.

**Comment by the-mace** [comment]
I found its possible to find them via inspection of the APK but the example in this commit is interesting as the field isn't used in the APK but it was known by someone previously so not sure how they discovered that.

**Comment by kaedenbrinkman** [comment]
Yes, there is likely a lot more info we can get by altering the GraphQL query. The GraphQL API is also used for their website, so this might be where this one came from. Back in June you could actually use a wildcard for the vehicle properties to return and would get back hundreds of data points about vehicle components. Sadly they've removed most of that info now :(

**Pull request merged**
